spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ajaypal
    password: ajaypal
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  version: Native dev production 1.0.0
