spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: "{cipher}AQAVVhcXb/j578bSBw/mmtdNur7q40aviwiI/fKK2hnMrCg1abr6di9J7CIEIoLFzN+om1D2giX3dGWN+4OiZecdWQGKMUPv8qVuUnLh6ade2qQhVydvK1yOosTXgrHBVItgUEGXzKeJwEcYCjbWh0t1MgxHWTnmJjef14N1ZLZEDJj3OjekyeDIEVY4oRGV4qUYQQnQgkoprrHnF9bR1yGj+LpUCBLMmiAyInpNZ2UIXXbp9NIH78E6k83gytisW0Zn/hTFJrSJhwkPgN6Ba8UwuG60IJjZEoWtDP70Axnhx+iEmNZyfs2ShlYS/JfoU0LiSDH8zO3bVFzzK6I3FvgbgUtBUpuAIoNZubKux+Uwdec2wbBI0Bs++F9/JOPdi84="
    password: ajaypal
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

app:
    version: 0.0.1
